//! `Arcane Absorption` (`BG35_911`) — Tier 4 token spell (`1` Gold), generated by `Leyline Surfacer`.
//!
//! Give a friendly Elemental half the stats of the highest-Health minion in the Tavern.

use super::targeted_tribe;
use crate::cards::CardHooks;
use crate::model::{Tribe, Unit};
use crate::rng::Rng;
use crate::tavern::{CardPool, TavernState};

/// Hooks registered for this spell in [`super::behaviors`].
pub fn hooks() -> CardHooks {
    targeted_tribe(Tribe::Elemental, cast)
}

/// `Arcane Absorption`: give a friendly Elemental half the stats of the highest-Health minion in
/// the Tavern.
pub fn cast(state: &mut TavernState, _: &Unit, board_pos: usize, _: &mut CardPool, rng: &mut Rng) {
    if board_pos < state.board.len() && state.board[board_pos].tribe.matches(Tribe::Elemental) {
        let max_hp = state
            .shop
            .iter()
            .filter(|u| !u.is_spell)
            .map(|u| u.health)
            .max();
        if let Some(best_hp) = max_hp {
            let candidates: Vec<(i32, i32)> = state
                .shop
                .iter()
                .filter(|u| !u.is_spell && u.health == best_hp)
                .map(|u| (u.attack / 2, u.health / 2))
                .collect();
            let (base_atk, base_hp) = if candidates.len() == 1 {
                candidates[0]
            } else {
                candidates[rng.below(candidates.len())]
            };
            let (atk, hp) = state.auras.spell_stat_buff(base_atk, base_hp);
            state.board[board_pos].add_stats(atk, hp);
        }
    }
}
