//! `Conflagration` (`BG35_910`) — Tier 4 token spell (`2` Gold), generated by `Firelands Fugitive`.
//!
//! Give a minion +4/+4, improved by each Elemental played this turn.

use super::targeted;
use crate::cards::CardHooks;
use crate::model::Unit;
use crate::rng::Rng;
use crate::tavern::{CardPool, TavernState};

/// Hooks registered for this spell in [`super::behaviors`].
pub fn hooks() -> CardHooks {
    targeted(cast)
}

/// `Conflagration`: give a minion +4/+4, plus +1/+1 per Elemental played this turn.
pub fn cast(state: &mut TavernState, _: &Unit, board_pos: usize, _: &mut CardPool, _: &mut Rng) {
    if board_pos < state.board.len() {
        let base = 4 + state.elementals_played_this_turn as i32;
        let (atk, hp) = state.auras.spell_stat_buff(base, base);
        state.board[board_pos].add_stats(atk, hp);
    }
}
