//! `Pointy Arrow` (`EBG_Spell_014`) — Tier 1 token spell (`1` Gold), generated by `Weapons Forge`.
//!
//! Give a minion +4 Attack.

use super::targeted;
use crate::cards::CardHooks;
use crate::model::Unit;
use crate::rng::Rng;
use crate::tavern::{CardPool, TavernState};

/// Hooks registered for this spell in [`super::behaviors`].
pub fn hooks() -> CardHooks {
    targeted(cast)
}

/// `Pointy Arrow`: give a minion +4 Attack.
pub fn cast(state: &mut TavernState, _: &Unit, board_pos: usize, _: &mut CardPool, _: &mut Rng) {
    if board_pos < state.board.len() {
        let (atk, hp) = state.auras.spell_stat_buff(4, 0);
        state.board[board_pos].add_stats(atk, hp);
    }
}
