//! Generated tokens, Choose-One option cards, and hand spell cards.

use crate::model::{CardId, Keyword, PlayerAuras, Tribe, Unit};

pub const TOKEN_ABERRANT_TENTACLE: CardId = 901;
pub const TOKEN_BEETLE: CardId = 902;
pub const TOKEN_MICROBOT: CardId = 903;
pub const TOKEN_SKELETON: CardId = 904;
pub const TOKEN_BAT: CardId = 905;
pub const TOKEN_WATER_DROPLET: CardId = 906;
pub const TOKEN_DEMON_FODDER: CardId = 907;
pub const TOKEN_FISHBAIT: CardId = 908;

pub const SPELL_BLOOD_GEM: CardId = 950;
pub const SPELL_TAVERN_COIN: CardId = 951;
pub const SPELL_LOCKBOX: CardId = 952;
pub const SPELL_GEM_DAY: CardId = 953;

// Choose-One sub-option cards (presented via `discover_pending`).
pub const CHOICE_CRATER_GEMS: CardId = 980;
pub const CHOICE_CRATER_GEM_DAY: CardId = 981;
pub const CHOICE_GEM_DAY_ATK: CardId = 982;
pub const CHOICE_GEM_DAY_HP: CardId = 983;
pub const CHOICE_BOTANIST_ATK: CardId = 984;
pub const CHOICE_BOTANIST_HP: CardId = 985;
pub const CHOICE_ALLIANCE_ATK: CardId = 986;
pub const CHOICE_ALLIANCE_HP: CardId = 987;

/// Returns `true` if `card_id` is a Choose-One option card rather than a physical unit/spell.
pub fn is_choice_option(card_id: CardId) -> bool {
    (CHOICE_CRATER_GEMS..=CHOICE_ALLIANCE_HP).contains(&card_id)
}

/// `Aberrant Tentacle` (`0/2` Aberration with Taunt, generated by `Zoatroid` and `Underrot Spawn`).
pub fn make_aberrant_tentacle() -> Unit {
    Unit::new("Aberrant Tentacle", 0, 2)
        .with_card_id(TOKEN_ABERRANT_TENTACLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Aberration)
        .with_keyword(Keyword::Taunt)
}

/// `Beetle` (`2/2` Beast, or `4/4` if Golden, plus `beetle_bonus_atk / beetle_bonus_hp`).
pub fn make_beetle(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 4 } else { 2 };
    let atk = base + auras.beetle_bonus_atk;
    let hp = base + auras.beetle_bonus_hp;
    let mut u = Unit::new("Beetle", atk, hp)
        .with_card_id(TOKEN_BEETLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u
}

/// `Microbot` (`1/1` Mech, or `2/2` if Golden, summoned by `Cord Puller`).
pub fn make_microbot(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Microbot", s, s)
        .with_card_id(TOKEN_MICROBOT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Mech)
        .with_golden(is_golden)
}

/// `Skeleton` (`1/1` Undead, or `2/2` if Golden, summoned by `Harmless Bonehead`).
pub fn make_skeleton(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 2 } else { 1 };
    let atk = base + auras.undead_bonus_attack;
    let mut u = Unit::new("Skeleton", atk, base)
        .with_card_id(TOKEN_SKELETON)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Undead)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u.undead_attack_applied = auras.undead_bonus_attack;
    u
}

/// `1/1` Beast (`2/2` if Golden) summoned by `Flittering Bat`.
pub fn make_flittering_beast(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Bat", s, s)
        .with_card_id(TOKEN_BAT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden)
}

/// `Water Droplet` (`3/3` Elemental generated by `Sellemental`).
pub fn make_water_droplet() -> Unit {
    Unit::new("Water Droplet", 3, 3)
        .with_card_id(TOKEN_WATER_DROPLET)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Elemental)
}

/// `Demon Fodder` (`2/2` Demon generated in shop by `Laboratory Assistant`).
pub fn make_demon_fodder(is_golden: bool) -> Unit {
    let s = if is_golden { 4 } else { 2 };
    Unit::new("Demon Fodder", s, s)
        .with_card_id(TOKEN_DEMON_FODDER)
        .with_tavern_tier(2)
        .with_tribe(Tribe::Demon)
        .with_golden(is_golden)
}

/// `Fishbait` (`0/1` Beast, or `0/2` if Golden, generated in shop by `Lurking Lionfish`).
/// Cannot gain stats; Deathrattle gives killer `+5/+5` (`+10/+10` if Golden).
pub fn make_fishbait(is_golden: bool) -> Unit {
    let hp = if is_golden { 2 } else { 1 };
    let mut u = Unit::new("Fishbait", 0, hp)
        .with_card_id(TOKEN_FISHBAIT)
        .with_tavern_tier(2)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden);
    u.cant_gain_stats = true;
    u
}

/// `Blood Gem` (`+1/+1` targeted spell card, scaled by `blood_gem_bonus_atk / hp` when cast).
pub fn make_blood_gem() -> Unit {
    let mut gem = Unit::new("Blood Gem", 1, 1).with_card_id(SPELL_BLOOD_GEM);
    gem.is_spell = true;
    gem
}

/// `Tavern Coin` (`+1 Gold` untargeted spell card, Tier 1, Cost 1).
pub fn make_tavern_coin() -> Unit {
    let mut coin = Unit::new("Tavern Coin", 0, 0)
        .with_card_id(SPELL_TAVERN_COIN)
        .with_tavern_tier(1);
    coin.is_spell = true;
    coin.spell_cost = 1;
    coin
}

/// `Lockbox` (`BG36_520t` — Unplayable spell in hand that opens in 5 turns for a Golden minion with a type).
pub fn make_lockbox() -> Unit {
    let mut box_card = Unit::new("Lockbox", 0, 0)
        .with_card_id(SPELL_LOCKBOX)
        .with_tavern_tier(2);
    box_card.is_spell = true;
    box_card.unplayable = true;
    box_card.lockbox_turns_left = 5;
    box_card
}

/// `Gem Day` (`BG31_893` — Choose One: Your Blood Gems give an extra +1 Attack this game; or +1 Health).
pub fn make_gem_day() -> Unit {
    let mut spell = Unit::new("Gem Day", 0, 0)
        .with_card_id(SPELL_GEM_DAY)
        .with_tavern_tier(2);
    spell.is_spell = true;
    spell
}

/// Helper to construct a Choose-One option card for `discover_pending`.
pub fn make_choice_option(card_id: CardId, name: &str, is_golden: bool) -> Unit {
    let mut u = Unit::new(name, 0, 0)
        .with_card_id(card_id)
        .with_golden(is_golden);
    u.is_spell = true;
    u
}
