//! Generated tokens and hand spell cards.

use crate::model::{CardId, Keyword, PlayerAuras, Tribe, Unit};

pub const TOKEN_ABERRANT_TENTACLE: CardId = 901;
pub const TOKEN_BEETLE: CardId = 902;
pub const TOKEN_MICROBOT: CardId = 903;
pub const TOKEN_SKELETON: CardId = 904;
pub const TOKEN_BAT: CardId = 905;

pub const SPELL_BLOOD_GEM: CardId = 950;
pub const SPELL_TAVERN_COIN: CardId = 951;

/// `Aberrant Tentacle` (`0/2` Aberration with Taunt, generated by `Zoatroid`).
pub fn make_aberrant_tentacle() -> Unit {
    Unit::new("Aberrant Tentacle", 0, 2)
        .with_card_id(TOKEN_ABERRANT_TENTACLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Aberration)
        .with_keyword(Keyword::Taunt)
}

/// `Beetle` (`2/2` Beast, or `4/4` if Golden, plus `beetle_bonus_atk / beetle_bonus_hp`).
pub fn make_beetle(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 4 } else { 2 };
    let atk = base + auras.beetle_bonus_atk;
    let hp = base + auras.beetle_bonus_hp;
    let mut u = Unit::new("Beetle", atk, hp)
        .with_card_id(TOKEN_BEETLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u
}

/// `Microbot` (`1/1` Mech, or `2/2` if Golden, summoned by `Cord Puller`).
pub fn make_microbot(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Microbot", s, s)
        .with_card_id(TOKEN_MICROBOT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Mech)
        .with_golden(is_golden)
}

/// `Skeleton` (`1/1` Undead, or `2/2` if Golden, summoned by `Harmless Bonehead`).
pub fn make_skeleton(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 2 } else { 1 };
    let atk = base + auras.undead_bonus_attack;
    let mut u = Unit::new("Skeleton", atk, base)
        .with_card_id(TOKEN_SKELETON)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Undead)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u
}

/// `1/1` Beast (`2/2` if Golden) summoned by `Flittering Bat`.
pub fn make_flittering_beast(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Bat", s, s)
        .with_card_id(TOKEN_BAT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden)
}

/// `Blood Gem` (`+1/+1` targeted spell card).
pub fn make_blood_gem() -> Unit {
    let mut gem = Unit::new("Blood Gem", 1, 1).with_card_id(SPELL_BLOOD_GEM);
    gem.is_spell = true;
    gem
}

/// `Tavern Coin` (`+1 Gold` untargeted spell card).
pub fn make_tavern_coin() -> Unit {
    let mut coin = Unit::new("Tavern Coin", 0, 0).with_card_id(SPELL_TAVERN_COIN);
    coin.is_spell = true;
    coin
}
