//! Generated tokens, Choose-One option cards, and hand spell cards.

use crate::cards::hooks::CardEventFn;
use crate::cards::{
    all_templates, check_stat_thresholds, on_card_added_to_hand, spells, tier2, tier3, tier4,
    tier5, tier6, CardFlags, CardHooks, CardTemplate,
};
use crate::model::{CardId, Keyword, PlayerAuras, Tribe, Unit};
use crate::rng::Rng;
use crate::tavern::TavernState;

pub const TOKEN_ABERRANT_TENTACLE: CardId = 901;
pub const TOKEN_BEETLE: CardId = 902;
pub const TOKEN_MICROBOT: CardId = 903;
pub const TOKEN_SKELETON: CardId = 904;
pub const TOKEN_BAT: CardId = 905;
pub const TOKEN_WATER_DROPLET: CardId = 906;
pub const TOKEN_DEMON_FODDER: CardId = 907;
pub const TOKEN_FISHBAIT: CardId = 908;
pub const TOKEN_HELPING_HAND: CardId = 909;
pub const TOKEN_SATELLITE: CardId = 910;
pub const TOKEN_SEWER_RAT: CardId = 911;
pub const TOKEN_HALF_SHELL: CardId = 912;
pub const TOKEN_MAGICFIN_APPRENTICE: CardId = 913;
pub const TOKEN_BLOOD_GOLEM: CardId = 914;

pub const TOKEN_BLUE_CHROMADRAKE: CardId = 920;
pub const TOKEN_BLACK_CHROMADRAKE: CardId = 921;
pub const TOKEN_GREEN_CHROMADRAKE: CardId = 922;
pub const TOKEN_BRONZE_CHROMADRAKE: CardId = 923;
pub const TOKEN_RED_CHROMADRAKE: CardId = 924;

pub const CHROMADRAKE_IDS: [CardId; 5] = [
    TOKEN_BLUE_CHROMADRAKE,
    TOKEN_BLACK_CHROMADRAKE,
    TOKEN_GREEN_CHROMADRAKE,
    TOKEN_BRONZE_CHROMADRAKE,
    TOKEN_RED_CHROMADRAKE,
];

pub const SPELL_BLOOD_GEM: CardId = 950;
pub const SPELL_TAVERN_COIN: CardId = 951;
pub const SPELL_LOCKBOX: CardId = 952;
pub const SPELL_GEM_DAY: CardId = 953;
pub const SPELL_SLUDGE_CORROSION: CardId = 954;
pub const SPELL_GEM_CONFISCATION: CardId = 955;
pub const SPELL_GOLDEN_TOUCH: CardId = 956;
pub const SPELL_POINTY_ARROW: CardId = 957;
pub const SPELL_ARCANE_ABSORPTION: CardId = 958;
pub const SPELL_CONFLAGRATION: CardId = 959;

// Choose-One / Hero Power sub-option cards (presented via `discover_pending`).
pub const CHOICE_BRIGAND_GEMS: CardId = 973;
pub const CHOICE_BRIGAND_BARRAGE: CardId = 974;
pub const CHOICE_HP_1: CardId = 975;
pub const CHOICE_HP_2: CardId = 976;
pub const CHOICE_HP_3: CardId = 977;
pub const CHOICE_FOREST_SINGLE: CardId = 978;
pub const CHOICE_FOREST_ALL: CardId = 979;
pub const CHOICE_CRATER_GEMS: CardId = 980;
pub const CHOICE_CRATER_GEM_DAY: CardId = 981;
pub const CHOICE_GEM_DAY_ATK: CardId = 982;
pub const CHOICE_GEM_DAY_HP: CardId = 983;
pub const CHOICE_BOTANIST_ATK: CardId = 984;
pub const CHOICE_BOTANIST_HP: CardId = 985;
pub const CHOICE_ALLIANCE_ATK: CardId = 986;
pub const CHOICE_ALLIANCE_HP: CardId = 987;
pub const CHOICE_FOODIE_BUFF_GEMS: CardId = 988;
pub const CHOICE_FOODIE_GET_GEMS: CardId = 989;
pub const CHOICE_SLY_REFRESHES: CardId = 990;
pub const CHOICE_SLY_GEMS: CardId = 991;
pub const CHOICE_SCARAB_REBORN: CardId = 992;
pub const CHOICE_SCARAB_WINDFURY: CardId = 993;
pub const CHOICE_TIME_MGMT_NOW: CardId = 994;
pub const CHOICE_TIME_MGMT_LATER: CardId = 995;
pub const CHOICE_BOUNDLESS_MINION: CardId = 996;
pub const CHOICE_BOUNDLESS_SPELL: CardId = 997;
pub const CHOICE_SNARE_QUILBOAR: CardId = 998;
pub const CHOICE_SNARE_MAX_GOLD: CardId = 999;

/// Returns `true` if `card_id` is a Choose-One option card rather than a physical unit/spell.
pub fn is_choice_option(card_id: CardId) -> bool {
    (CHOICE_BRIGAND_GEMS..=CHOICE_SNARE_MAX_GOLD).contains(&card_id)
}

/// `Aberrant Tentacle` (`0/2` Aberration with Taunt, generated by `Zoatroid` and `Underrot Spawn`).
pub fn make_aberrant_tentacle() -> Unit {
    Unit::new("Aberrant Tentacle", 0, 2)
        .with_card_id(TOKEN_ABERRANT_TENTACLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Aberration)
        .with_keyword(Keyword::Taunt)
}

/// `Beetle` (`2/2` Beast, or `4/4` if Golden, plus `beetle_bonus_atk / beetle_bonus_hp`).
pub fn make_beetle(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 4 } else { 2 };
    let atk = base + auras.beetle_bonus_atk;
    let hp = base + auras.beetle_bonus_hp;
    let mut u = Unit::new("Beetle", atk, hp)
        .with_card_id(TOKEN_BEETLE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u
}

/// `Microbot` (`1/1` Mech, or `2/2` if Golden, summoned by `Cord Puller`).
pub fn make_microbot(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Microbot", s, s)
        .with_card_id(TOKEN_MICROBOT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Mech)
        .with_golden(is_golden)
}

/// `Skeleton` (`1/1` Undead, or `2/2` if Golden, summoned by `Harmless Bonehead` / `Cadaver Caretaker`).
pub fn make_skeleton(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let base = if is_golden { 2 } else { 1 };
    let atk = base + auras.undead_bonus_attack;
    let mut u = Unit::new("Skeleton", atk, base)
        .with_card_id(TOKEN_SKELETON)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Undead)
        .with_golden(is_golden);
    u.base_attack = base;
    u.base_health = base;
    u.undead_attack_applied = auras.undead_bonus_attack;
    u
}

/// `Helping Hand` (`2/1` Undead with Reborn, summoned by `Handless Forsaken`).
pub fn make_helping_hand(is_golden: bool, auras: &PlayerAuras) -> Unit {
    let (base_atk, base_hp) = if is_golden { (4, 2) } else { (2, 1) };
    let atk = base_atk + auras.undead_bonus_attack;
    let mut u = Unit::new("Helping Hand", atk, base_hp)
        .with_card_id(TOKEN_HELPING_HAND)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Undead)
        .with_keyword(Keyword::Reborn)
        .with_golden(is_golden);
    u.base_attack = base_atk;
    u.base_health = base_hp;
    u.undead_attack_applied = auras.undead_bonus_attack;
    u
}

/// Instantiate one of the 5 `Chromadrake` token minions (`BG34_634t`..`BG34_638t`, generated by `Hired Mount`).
pub fn make_chromadrake(card_id: CardId, is_golden: bool) -> Unit {
    let m = if is_golden { 2 } else { 1 };
    let (name, atk, hp) = match card_id {
        TOKEN_BLUE_CHROMADRAKE => ("Blue Chromadrake", 4 * m, 4 * m),
        TOKEN_BLACK_CHROMADRAKE => ("Black Chromadrake", 4 * m, 6 * m),
        TOKEN_GREEN_CHROMADRAKE => ("Green Chromadrake", 3 * m, 5 * m),
        TOKEN_BRONZE_CHROMADRAKE => ("Bronze Chromadrake", 5 * m, 3 * m),
        TOKEN_RED_CHROMADRAKE => ("Red Chromadrake", 6 * m, 4 * m),
        _ => ("Blue Chromadrake", 4 * m, 4 * m),
    };
    Unit::new(name, atk, hp)
        .with_card_id(card_id)
        .with_tavern_tier(3)
        .with_tribe(Tribe::Dragon)
        .with_golden(is_golden)
}

/// `1/1` Beast (`2/2` if Golden) summoned by `Flittering Bat`.
pub fn make_flittering_beast(is_golden: bool) -> Unit {
    let s = if is_golden { 2 } else { 1 };
    Unit::new("Bat", s, s)
        .with_card_id(TOKEN_BAT)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden)
}

/// `Water Droplet` (`3/3` Elemental generated by `Sellemental`).
pub fn make_water_droplet() -> Unit {
    Unit::new("Water Droplet", 3, 3)
        .with_card_id(TOKEN_WATER_DROPLET)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Elemental)
}

/// `Demon Fodder` (`2/2` Demon generated in shop by `Laboratory Assistant` / `Trapped Clapper`).
pub fn make_demon_fodder(is_golden: bool) -> Unit {
    let s = if is_golden { 4 } else { 2 };
    Unit::new("Demon Fodder", s, s)
        .with_card_id(TOKEN_DEMON_FODDER)
        .with_tavern_tier(2)
        .with_tribe(Tribe::Demon)
        .with_golden(is_golden)
}

/// `Fishbait` (`0/1` Beast, or `0/2` if Golden, generated in shop by `Lurking Lionfish`).
/// Cannot gain stats; Deathrattle gives killer `+5/+5` (`+10/+10` if Golden).
pub fn make_fishbait(is_golden: bool) -> Unit {
    let hp = if is_golden { 2 } else { 1 };
    let mut u = Unit::new("Fishbait", 0, hp)
        .with_card_id(TOKEN_FISHBAIT)
        .with_tavern_tier(2)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden);
    u.cant_gain_stats = true;
    u
}

/// `Blood Gem` (`+1/+1` targeted spell card, scaled by `blood_gem_bonus_atk / hp` when cast).
pub fn make_blood_gem() -> Unit {
    let mut gem = Unit::new("Blood Gem", 1, 1).with_card_id(SPELL_BLOOD_GEM);
    gem.is_spell = true;
    gem
}

/// `Tavern Coin` (`+1 Gold` untargeted spell card, Tier 1, Cost 1).
pub fn make_tavern_coin() -> Unit {
    let mut coin = Unit::new("Tavern Coin", 0, 0)
        .with_card_id(SPELL_TAVERN_COIN)
        .with_tavern_tier(1);
    coin.is_spell = true;
    coin.spell_cost = 1;
    coin
}

/// `Lockbox` (`BG36_520t` — Unplayable spell in hand that opens in 5 turns for a Golden minion with a type).
pub fn make_lockbox() -> Unit {
    let mut box_card = Unit::new("Lockbox", 0, 0)
        .with_card_id(SPELL_LOCKBOX)
        .with_tavern_tier(2);
    box_card.is_spell = true;
    box_card.unplayable = true;
    box_card.lockbox_turns_left = 5;
    box_card
}

/// `Lockbox` in hand at the start of your turn: count down, and open once the countdown ends.
fn lockbox_turn_start(state: &mut TavernState, hand_idx: usize, rng: &mut Rng) {
    let lockbox = &mut state.hand[hand_idx];
    lockbox.lockbox_turns_left = lockbox.lockbox_turns_left.saturating_sub(1);
    if lockbox.lockbox_turns_left == 0 {
        open_lockbox(state, hand_idx, rng);
    }
}

/// `Lockbox` in hand: open it if its countdown has already ended (e.g. sped up in combat).
fn lockbox_ready(state: &mut TavernState, hand_idx: usize, rng: &mut Rng) {
    if state.hand[hand_idx].lockbox_turns_left == 0 {
        open_lockbox(state, hand_idx, rng);
    }
}

/// Open the `Lockbox` at `state.hand[hand_idx]`, replacing it with a random Golden minion of your
/// Tier with a type.
pub fn open_lockbox(state: &mut TavernState, hand_idx: usize, rng: &mut Rng) {
    if hand_idx >= state.hand.len() || state.hand[hand_idx].card_id != SPELL_LOCKBOX {
        return;
    }
    let target_tier = state.tavern_tier.max(1);
    let typed = |t: &&CardTemplate| t.tribe != Tribe::None && !t.intrinsic_golden;
    let mut typed_templates: Vec<&CardTemplate> = all_templates()
        .iter()
        .filter(|t| typed(t) && t.tavern_tier == target_tier)
        .collect();
    if typed_templates.is_empty() {
        typed_templates = all_templates()
            .iter()
            .filter(|t| typed(t) && t.tavern_tier <= target_tier)
            .collect();
    }
    if typed_templates.is_empty() {
        return;
    }
    let pick = rng.below(typed_templates.len());
    let mut golden = typed_templates[pick].instantiate();
    golden.make_golden();
    golden.intrinsic_golden = false;
    state.apply_global_unit_auras(&mut golden);
    check_stat_thresholds(&mut golden);
    state.hand[hand_idx] = golden;
    on_card_added_to_hand(&state.board, &mut state.auras);
}

/// `Gem Day` (`BG31_893` — Choose One: Your Blood Gems give an extra +1 Attack this game; or +1 Health).
pub fn make_gem_day() -> Unit {
    let mut spell = Unit::new("Gem Day", 0, 0)
        .with_card_id(SPELL_GEM_DAY)
        .with_tavern_tier(2);
    spell.is_spell = true;
    spell.spell_cost = 1;
    spell
}

/// `Sludge Corrosion` (`BG36_301t` — Give your minions +1/+1. If you discard this, cast it twice).
pub fn make_sludge_corrosion() -> Unit {
    let mut spell = Unit::new("Sludge Corrosion", 0, 0)
        .with_card_id(SPELL_SLUDGE_CORROSION)
        .with_tavern_tier(4);
    spell.is_spell = true;
    spell.spell_cost = 1;
    spell
}

/// `Gem Confiscation` (`BG28_698` — Plays 3 Blood Gems on a minion and steals all Blood Gems from its neighbors).
pub fn make_gem_confiscation() -> Unit {
    let mut spell = Unit::new("Gem Confiscation", 0, 0)
        .with_card_id(SPELL_GEM_CONFISCATION)
        .with_tavern_tier(4);
    spell.is_spell = true;
    spell.spell_cost = 1;
    spell
}

/// `Golden Touch` (`BG28_830` — Make a random minion in the Tavern Golden).
pub fn make_golden_touch() -> Unit {
    let mut spell = Unit::new("Golden Touch", 0, 0)
        .with_card_id(SPELL_GOLDEN_TOUCH)
        .with_tavern_tier(5);
    spell.is_spell = true;
    spell.spell_cost = 5;
    spell
}

/// `Satellite` (`BG34_Giant_610t` — `4/4` Magnetic Mech, or `8/8` if Golden, magnetized by `Glambot`).
pub fn make_satellite(is_golden: bool) -> Unit {
    let s = if is_golden { 8 } else { 4 };
    Unit::new("Satellite", s, s)
        .with_card_id(TOKEN_SATELLITE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Mech)
        .with_keyword(Keyword::Magnetic)
        .with_golden(is_golden)
}

/// `Pointy Arrow` (`EBG_Spell_014` — Give a minion +4 Attack, generated by `Weapons Forge`).
pub fn make_pointy_arrow() -> Unit {
    let mut spell = Unit::new("Pointy Arrow", 0, 0)
        .with_card_id(SPELL_POINTY_ARROW)
        .with_tavern_tier(1);
    spell.is_spell = true;
    spell.spell_cost = 1;
    spell
}

/// `Arcane Absorption` (`BG35_911` — Give a friendly Elemental half the stats of the highest-Health minion in the Tavern, generated by `Leyline Surfacer`).
pub fn make_arcane_absorption() -> Unit {
    let mut spell = Unit::new("Arcane Absorption", 0, 0)
        .with_card_id(SPELL_ARCANE_ABSORPTION)
        .with_tavern_tier(4);
    spell.is_spell = true;
    spell.spell_cost = 1;
    spell
}

/// `Conflagration` (`BG35_910` — Give a minion +4/+4, improved by each Elemental played this turn, generated by `Firelands Fugitive`).
pub fn make_conflagration() -> Unit {
    let mut spell = Unit::new("Conflagration", 0, 0)
        .with_card_id(SPELL_CONFLAGRATION)
        .with_tavern_tier(4);
    spell.is_spell = true;
    spell.spell_cost = 2;
    spell
}

/// `Sewer Rat` (`BG19_010` — `3/2` Beast, or `6/4` if Golden, summoned by `Sewer Lord`; Deathrattle: Summon a 2/3 Turtle with Taunt).
pub fn make_sewer_rat(is_golden: bool) -> Unit {
    let (atk, hp) = if is_golden { (6, 4) } else { (3, 2) };
    Unit::new("Sewer Rat", atk, hp)
        .with_card_id(TOKEN_SEWER_RAT)
        .with_tavern_tier(2)
        .with_tribe(Tribe::Beast)
        .with_golden(is_golden)
}

/// `Half-Shell` (`BG19_010t` — `2/3` Beast with Taunt, or `4/6` if Golden, summoned by `Sewer Rat`).
pub fn make_half_shell(is_golden: bool) -> Unit {
    let (atk, hp) = if is_golden { (4, 6) } else { (2, 3) };
    Unit::new("Half-Shell", atk, hp)
        .with_card_id(TOKEN_HALF_SHELL)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Beast)
        .with_keyword(Keyword::Taunt)
        .with_golden(is_golden)
}

/// `Magicfin Apprentice` (`BG33_890t` — `1/1` Murloc taught a Tavern spell by `Magicfin Mycologist`; cannot be tripled).
pub fn make_magicfin_apprentice(taught_spell_id: CardId) -> Unit {
    let mut u = Unit::new("Magicfin Apprentice", 1, 1)
        .with_card_id(TOKEN_MAGICFIN_APPRENTICE)
        .with_tavern_tier(1)
        .with_tribe(Tribe::Murloc);
    u.taught_spell_id = Some(taught_spell_id);
    u
}

/// `Blood Golem` (`BG23_013t` — Token summoned by `Jailbird Juggernaut` with dynamic stats).
pub fn make_blood_golem(atk: i32, hp: i32, is_golden: bool) -> Unit {
    Unit::new("Blood Golem", atk, hp)
        .with_card_id(TOKEN_BLOOD_GOLEM)
        .with_tavern_tier(1)
        .with_golden(is_golden)
}

/// Helper to construct a Choose-One option card for `discover_pending`.
pub fn make_choice_option(card_id: CardId, name: &str, is_golden: bool) -> Unit {
    let mut u = Unit::new(name, 0, 0)
        .with_card_id(card_id)
        .with_golden(is_golden);
    u.is_spell = true;
    u
}

/// Instantiate a plain (non-Golden, unbuffed) copy of a token minion by `card_id`.
pub fn make_plain_token(unit: &Unit, auras: &PlayerAuras) -> Option<Unit> {
    match unit.card_id {
        TOKEN_ABERRANT_TENTACLE => Some(make_aberrant_tentacle()),
        TOKEN_BEETLE => Some(make_beetle(false, auras)),
        TOKEN_MICROBOT => Some(make_microbot(false)),
        TOKEN_SKELETON => Some(make_skeleton(false, auras)),
        TOKEN_BAT => Some(make_flittering_beast(false)),
        TOKEN_WATER_DROPLET => Some(make_water_droplet()),
        TOKEN_DEMON_FODDER => Some(make_demon_fodder(false)),
        TOKEN_FISHBAIT => Some(make_fishbait(false)),
        TOKEN_HELPING_HAND => Some(make_helping_hand(false, auras)),
        TOKEN_SATELLITE => Some(make_satellite(false)),
        TOKEN_SEWER_RAT => Some(make_sewer_rat(false)),
        TOKEN_HALF_SHELL => Some(make_half_shell(false)),
        TOKEN_MAGICFIN_APPRENTICE => {
            Some(make_magicfin_apprentice(unit.taught_spell_id.unwrap_or(0)))
        }
        TOKEN_BLOOD_GOLEM => Some(make_blood_golem(1, 1, false)),
        TOKEN_BLUE_CHROMADRAKE
        | TOKEN_BLACK_CHROMADRAKE
        | TOKEN_GREEN_CHROMADRAKE
        | TOKEN_BRONZE_CHROMADRAKE
        | TOKEN_RED_CHROMADRAKE => Some(make_chromadrake(unit.card_id, false)),
        _ => None,
    }
}

/// Behaviour tables for tokens with card text (registered in the card registry).
pub fn behaviors() -> Vec<(CardId, CardHooks)> {
    let chromadrake = CardHooks::EMPTY.on_battlecry(|state, unit, _, _, rng| {
        tier3::hired_mount::on_chromadrake_battlecry(state, unit, rng)
    });
    let mut out = vec![
        (
            TOKEN_MAGICFIN_APPRENTICE,
            CardHooks::EMPTY.on_battlecry(|state, unit, board_pos, pool, rng| {
                tier6::magicfin_mycologist::on_apprentice_battlecry(
                    state, unit, board_pos, pool, rng,
                )
            }),
        ),
        (
            TOKEN_SEWER_RAT,
            CardHooks::EMPTY.on_deathrattle(tier5::sewer_lord::on_sewer_rat_deathrattle),
        ),
        (
            SPELL_SLUDGE_CORROSION,
            CardHooks::EMPTY.on_discarded(|state, _, pool, rng| {
                // Discarded: cast it twice.
                for _ in 0..2 {
                    state.auras.spells_played += 1;
                    spells::cast_spell(state, make_sludge_corrosion(), 0, pool, rng);
                }
            }),
        ),
        (
            SPELL_LOCKBOX,
            CardHooks::EMPTY
                .on_turn_start_in_hand(lockbox_turn_start)
                .on_ready_in_hand(lockbox_ready),
        ),
    ];
    out.extend(CHROMADRAKE_IDS.iter().map(|&id| (id, chromadrake)));
    out.extend(choose_one_options().into_iter().map(|(id, on_chosen)| {
        let option = CardHooks::EMPTY.on_chosen(on_chosen);
        (id, option.with_flags(CardFlags::CHOOSE_ONE_OPTION))
    }));
    out.extend(
        [CHOICE_HP_1, CHOICE_HP_2, CHOICE_HP_3]
            .map(|id| (id, CardHooks::EMPTY.on_chosen(spells::choose_hero_power))),
    );
    out
}

/// Effects of the Choose-One option cards (`on_chosen` hooks), defined with the card or spell
/// that offers them.
fn choose_one_options() -> [(CardId, CardEventFn); 24] {
    use tier2::{crater_miner, intrepid_botanist};
    use tier3::{fearless_foodie, sly_infiltrator, sprightly_scarab};
    use tier4::snare_trapper;
    use tier6::veteran_brigand;
    [
        (CHOICE_BRIGAND_GEMS, veteran_brigand::choose_gems),
        (CHOICE_BRIGAND_BARRAGE, veteran_brigand::choose_barrage),
        (CHOICE_FOREST_SINGLE, spells::choose_forest_single),
        (CHOICE_FOREST_ALL, spells::choose_forest_all),
        (CHOICE_CRATER_GEMS, crater_miner::choose_gems),
        (CHOICE_CRATER_GEM_DAY, crater_miner::choose_gem_day),
        (CHOICE_GEM_DAY_ATK, spells::choose_gem_day_atk),
        (CHOICE_GEM_DAY_HP, spells::choose_gem_day_hp),
        (CHOICE_BOTANIST_ATK, intrepid_botanist::choose_atk),
        (CHOICE_BOTANIST_HP, intrepid_botanist::choose_hp),
        (CHOICE_ALLIANCE_ATK, spells::choose_alliance_atk),
        (CHOICE_ALLIANCE_HP, spells::choose_alliance_hp),
        (CHOICE_FOODIE_BUFF_GEMS, fearless_foodie::choose_buff_gems),
        (CHOICE_FOODIE_GET_GEMS, fearless_foodie::choose_get_gems),
        (CHOICE_SLY_REFRESHES, sly_infiltrator::choose_refreshes),
        (CHOICE_SLY_GEMS, sly_infiltrator::choose_gems),
        (CHOICE_SCARAB_REBORN, sprightly_scarab::choose_reborn),
        (CHOICE_SCARAB_WINDFURY, sprightly_scarab::choose_windfury),
        (CHOICE_TIME_MGMT_NOW, spells::choose_time_now),
        (CHOICE_TIME_MGMT_LATER, spells::choose_time_later),
        (CHOICE_BOUNDLESS_MINION, spells::choose_boundless_minion),
        (CHOICE_BOUNDLESS_SPELL, spells::choose_boundless_spell),
        (CHOICE_SNARE_QUILBOAR, snare_trapper::choose_quilboar),
        (CHOICE_SNARE_MAX_GOLD, snare_trapper::choose_max_gold),
    ]
}
